openapi: 3.0.1
info:
  title: Hassio API
  description: >-
    This api compiles the profile of the connected users
  version: '1.0'
servers:
  - url: '/api/v1'
    description: Version1
tags:
  - name: Profile
paths:
  /profile:
    get:
      tags:
        - Profile
      summary: Get the profile
      operationId: getProfile
      parameters:
        - name: id
          in: query
          description: The id/token of the mobile device
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/200'
        '404':
          $ref: '#/components/responses/404'
components:
  schemas:
    Profile:
      type: object
      properties:
        e_present:
          type: boolean
          example: true
        e_id: 
          type: string
          example: 1
        e_name:
          type: string 
          example: Daniel
        icon: 
          type: string
          example: urlIcon
        goals:
          type: array
          items:
            $ref: '#/components/schemas/Goal'
        skills:
          type: array
          items:
            $ref: '#/components/schemas/Skill'
    Goal:
      type: object
      properties:
        name:
          type: string
          example: 'g_sh_switch'
        value:
          type: string
          example: 'off'
    Skill:
      type: object
      properties:
        name:
          type: string
          example: 'sk_cleanac'
        value:
          type: string
          example: 'off'
        endpoint:
          type: string
          example: 'endpoint'
  responses:
    '200':
      description: Successful response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Profile'
    '404':
      description: Not found response
      content:
        text/plain:
          schema:
            title: Endpoint not found
            type: string
            example: Not found
