openapi: 3.0.1
info:
  title: Alerta API
  description: >-
    Esta API provee diferentes servicios para guardar información sobre las
    distintas alertas y la localización del dispositivo.
  version: '1.0'
  termsOfService: 'https://asistex.es/terms'
  contact:
    name: Alerta API
    url: 'https://asistex.es/terms'
    email: asistex@gmail.com
servers:
  - url: 'https://alertaapi-asistex.herokuapp.com/'
    description: Heroku server
paths:
  /alerta/caida:
    post:
      tags:
        - Alertas
      summary: Alerta de tipo caida
      description: Guarda alerta de tipo caida en el servidor.
      requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alerta'
            text/plain:
              schema:
                type: string
      responses:
        '201':
          $ref: '#/components/responses/201'
        '404':
          $ref: '#/components/responses/404'
        '405':
          $ref: '#/components/responses/405'
 
  /alerta/localizacion:
    post:
      tags:
        - Alertas
      summary: Alerta de tipo localizacion no permitida
      description: Guarda alerta de tipo localizacion no permitida en el servidor.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alerta'
          text/plain:
            schema:
              type: string
      responses:
        '201':
          $ref: '#/components/responses/201'
        '404':
          $ref: '#/components/responses/404'
        '405':
          $ref: '#/components/responses/405'
  /alerta/bateria:
    post:
      tags:
        - Alertas
      summary: Alerta del nivel bajo de bateria del dispositivo.
      description: Registra alerta sobre el nivel bajo de bateria del dispositivo.
      requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertaBateria'
            text/plain:
              schema:
                type: string
      responses:
        '201':
          $ref: '#/components/responses/201'
        '404':
          $ref: '#/components/responses/404'
        '405':
          $ref: '#/components/responses/405'
  /localizacion:
    post:
      tags:
        - Localización
      summary: Localización de una persona
      description: Registra la localización de una persona
      requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alerta'
            text/plain:
              schema:
                type: string
      responses:
        '201':
          $ref: '#/components/responses/201'
        '404':
          $ref: '#/components/responses/404'
        '405':
          $ref: '#/components/responses/405'
components:
  schemas:
    Alerta:
      type: object
      properties:
        idPersona:
          type: integer
          format: int64
        fecha:
          type: string
          format: date
          example: '2018-11-10'
        hora:
          type: string
          format: time
          example: '19:00'
        localizacion:
          $ref: '#/components/schemas/Localizacion'
    AlertaBateria:
      type: object
      properties:
        idPersona:
          type: integer
          format: int64
        fecha:
          type: string
          format: date
          example: '2018-11-10'
        hora:
          type: string
          format: time
          example: '19:00'
        nivelBateria:
          type: integer
          format: int64
          example: 25
    Localizacion:
      type: object
      properties:
        latitud:
          type: number
          format: float
          example: 38.5146304
        longitud:
          type: number
          format: float
          example: -6.8490971
  responses:
    '200':
      description: Successful response
      content:
        text/plain:
          schema:
            type: boolean
            example: true
    '201':
      description: Created
      content:
        text/plain:
            schema:
              title: Created
              type: string
              example: Created
    '404':
      description: Not found response
      content:
        text/plain:
          schema:
            title: Endpoint not found
            type: string
            example: Not found
    '405':
          description: Invalid input
